/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  platform: [{ type: 'autogenerated', dirName: 'platform' }],
  opensource: [{ type: 'autogenerated', dirName: 'open-source' }],
  launch: [{ type: 'autogenerated', dirName: 'launch' }],
  train: [{ type: 'autogenerated', dirName: 'train' }],
  deploy: [{ type: 'autogenerated', dirName: 'deploy' }],
  federate: [{ type: 'autogenerated', dirName: 'federate' }],
  workflow: [{ type: 'autogenerated', dirName: 'workflow' }],
  storage: [{ type: 'autogenerated', dirName: 'storage' }],
  community: [{ type: 'autogenerated', dirName: 'community' }],
  shareAndEarn: [{ type: 'autogenerated', dirName: 'share-and-earn'}]
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
